### ISSUE TITLE
Landing Language Switcher doesn’t work

### ISSUE THREAD

**Issue by SiravitPhokeed** [suankularb-wittayalai-school/mysk-frontend#116]
**Describe the bug**
Clicking/tapping the Language Switcher (Icon Button next to Help) doesn't change the language, instead always redirecting to Landing with the user’s language.

**To Reproduce**

1. Go to `/`
2. Click on Language Switcher
3. See that nothing happened

**Expected behavior**
The Language Switcher changes the language.

**Additional context**
A solution would be to store the user language, maybe in a cookie or as user metadata server-side, and only redirect to browser language in its absence.

**Comment by Jimmy-Tempest** [comment]
This is more complicated than we think it is since if the user is not logged in but wants to switch languages then that has to be done on the client side while if they do log in they would want the same for all of their devices which would require the server side. However, all first-time users would need to use the browser language. So, in the end, we would need to use both the client-side and server-side approach except if we want to make everything simpler we could just do the client side only. However, all the redirecting is currently done on the middleware which we do not have access to users' local storage making the server side our only choice which means unauthenticated users can not change their language.

**Comment by SiravitPhokeed** [comment]
Do we need the Language Switcher when not logged in if it already checks the browser language? Since a user is logged in forever (until log out), if the user wants to change the language, they can just log in and change the language in Preferences (which we’ll store on Supabase). They should still be able to use the site logged out because they wouldn’t set their browser language to a language they don’t understand.

Or we just use cookies. That’s an option, right?

**Comment by Jimmy-Tempest** [comment]
We need to account for foreign language teacher using school computers with language set to Thai as well

**Comment by SiravitPhokeed** [comment]
This is fixed, right?

**Comment by Jimmy-Tempest** [comment]
I think so
