### ISSUE TITLE
Add a way for teacher to delete an elective period

### ISSUE THREAD

**Issue by Temp9699** [suankularb-wittayalai-school/mysk-frontend#138]
**Is your feature request related to a problem? Please describe.**
Currently, teachers don’t have a way to delete any subject in an elective period. 

**Describe the solution you’d like**
A suggestion is to add “delete period” button for each subjects when the elective period is expanded as a way for teacher to delete a subject. After deleting a subject from an elective period, if there is only 1 subject left in that period, it should also automatically become normal period.

**Comment by SiravitPhokeed** [comment]
A teacher cannot create an Elective Period. The implementation of Elective Period is basically that multiple teachers add a period in the same location for the same class, and the students in that class see a stack of periods collectively called “Elective Period.”

Since a teacher cannot add many periods in the same location to create an Elective Period, they shouldn’t be able to “delete” it. Can you specify more about what happened?

**Comment by Temp9699** [comment]
So I tested by creating 2 subjects taught by the same teacher, starts at the same time, but at a different class and not necessarily have to be the same subject which later shows up as an elective period as shown in the attached photo. However, there is no way to delete any subjects in that elective period.

I think it could be a possible problem when released for teacher to use. For example, if a teacher wants to add a new period but accidentally drag and drop it into an existing period. The problem is that there is no way for them to fix that since they can’t delete the subject they accidentally created. Therefore I think either add a button for the teacher to delete a subject or prevent this from happening.
![C9D9E051-78E5-4188-A726-AAA9578DB61E](https://user-images.githubusercontent.com/67576074/230324048-a219b3f5-6471-48a4-afcf-e6f1ba587e73.png)
